import type { ExportRow } from './exportCsv';

export interface ForecastRow {
  month: string;
  takeHome: number;
  totalExpenses: number;
  debtPayment: number;
  liquidCash: number;
  endingCash: number;
  netWorth: number;
  debtBalance: number;
  savingsBalance: number;
}

export interface DashboardSnapshot {
  month: string;
  liquidCash: number;
  netWorth: number;
  income: number;
  expenses: number;
  totalDebtPayments: number;
  savingsRate: number;
  totalSaved: number;
  ccDebt: number;
}

export function exportTransactionsPdf(rows: ExportRow[], period = 'All Time'): void {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const htmlRows = rows.map(r => {
    const sign = r.type === 'income' ? '+' : '-';
    const amt = `${sign}$${Number(r.amount ?? 0).toFixed(2)}`;
    const cls = r.type === 'income' ? 'income' : 'expense';
    return `<tr>
      <td>${r.date ?? ''}</td>
      <td>${(r.note ?? '—').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</td>
      <td>${r.category ?? ''}</td>
      <td class="${cls}">${r.type ?? ''}</td>
      <td>${(r.payment_source ?? '—').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</td>
      <td class="amount ${cls}">${amt}</td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Forged — Transactions</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; font-size: 11px; color: #111827; padding: 24px; }
    header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 16px; padding-bottom: 10px; border-bottom: 2px solid #111; }
    h1 { font-size: 15px; font-weight: 700; letter-spacing: -0.03em; }
    .meta { font-size: 10px; color: #6b7280; margin-top: 2px; }
    .right { text-align: right; }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    th { text-align: left; padding: 5px 6px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.07em; border-bottom: 1px solid #111; color: #374151; }
    th:last-child { text-align: right; }
    td { padding: 5px 6px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    .amount { font-weight: 600; text-align: right; }
    tr:last-child td { border-bottom: none; }
    footer { margin-top: 16px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #9ca3af; }
    @media print { @page { margin: 1.5cm; size: A4 portrait; } body { padding: 0; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>FORGED</h1>
      <p class="meta">Transactions &middot; ${period}</p>
    </div>
    <div class="right meta">
      <p>Exported ${exportDate}</p>
      <p>${rows.length} transaction${rows.length !== 1 ? 's' : ''}</p>
    </div>
  </header>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Note</th>
        <th>Category</th>
        <th>Type</th>
        <th>Source</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>${htmlRows}</tbody>
  </table>
  <footer>Generated by Forged &middot; app.treforged.com</footer>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert('Allow pop-ups to export PDF, then try again.');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.addEventListener('load', () => { win.focus(); win.print(); });
}

function openPrintWindow(html: string): void {
  const win = window.open('', '_blank');
  if (!win) { alert('Allow pop-ups to export PDF, then try again.'); return; }
  win.document.write(html);
  win.document.close();
  win.addEventListener('load', () => { win.focus(); win.print(); });
}

const PDF_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, -apple-system, sans-serif; font-size: 11px; color: #111827; padding: 24px; }
  header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 16px; padding-bottom: 10px; border-bottom: 2px solid #111; }
  h1 { font-size: 15px; font-weight: 700; letter-spacing: -0.03em; }
  .meta { font-size: 10px; color: #6b7280; margin-top: 2px; }
  .right { text-align: right; }
  table { width: 100%; border-collapse: collapse; margin-top: 4px; }
  th { text-align: left; padding: 5px 6px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.07em; border-bottom: 1px solid #111; color: #374151; }
  th:last-child, td:last-child { text-align: right; }
  td { padding: 5px 6px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
  .pos { color: #16a34a; font-weight: 600; }
  .neg { color: #dc2626; font-weight: 600; }
  .num { text-align: right; }
  tr:last-child td { border-bottom: none; }
  .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 12px 0 16px; }
  .kpi { padding: 10px 12px; border: 1px solid #e5e7eb; border-radius: 6px; }
  .kpi-label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.07em; color: #6b7280; }
  .kpi-value { font-size: 15px; font-weight: 700; margin-top: 2px; letter-spacing: -0.02em; }
  footer { margin-top: 16px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #9ca3af; }
  @media print { @page { margin: 1.5cm; size: A4 portrait; } body { padding: 0; } }
`;

function fmt(n: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
}

export function exportForecastPdf(rows: ForecastRow[], period = 'All Time'): void {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const htmlRows = rows.map(r => {
    const cashCls = r.endingCash < 0 ? 'neg' : '';
    const nwCls = r.netWorth < 0 ? 'neg' : 'pos';
    return `<tr>
      <td>${r.month}</td>
      <td class="num pos">${fmt(r.takeHome)}</td>
      <td class="num neg">−${fmt(r.totalExpenses)}</td>
      <td class="num neg">−${fmt(r.debtPayment)}</td>
      <td class="num ${cashCls}">${fmt(r.endingCash)}</td>
      <td class="num">${fmt(r.savingsBalance)}</td>
      <td class="num ${r.debtBalance > 0 ? 'neg' : ''}">${fmt(r.debtBalance)}</td>
      <td class="num ${nwCls}">${fmt(r.netWorth)}</td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Forged — Forecast</title><style>${PDF_STYLES}</style></head>
<body>
  <header>
    <div><h1>FORGED</h1><p class="meta">36-Month Forecast &middot; ${period}</p></div>
    <div class="right meta"><p>Exported ${exportDate}</p><p>${rows.length} month${rows.length !== 1 ? 's' : ''}</p></div>
  </header>
  <table>
    <thead><tr>
      <th>Month</th><th>Take-Home</th><th>Expenses</th><th>Debt Pmt</th><th>End Cash</th><th>Savings</th><th>Debt Bal</th><th>Net Worth</th>
    </tr></thead>
    <tbody>${htmlRows}</tbody>
  </table>
  <footer>Generated by Forged &middot; app.treforged.com</footer>
</body></html>`;

  openPrintWindow(html);
}

export function exportDashboardPdf(snap: DashboardSnapshot): void {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const kpis = [
    { label: 'Liquid Cash', value: fmt(snap.liquidCash) },
    { label: 'Net Worth', value: fmt(snap.netWorth) },
    { label: 'Monthly Income', value: fmt(snap.income) },
    { label: 'Monthly Expenses', value: fmt(snap.expenses) },
    { label: 'Debt Payments', value: fmt(snap.totalDebtPayments) },
    { label: 'Savings Rate', value: `${snap.savingsRate.toFixed(1)}%` },
    { label: 'Total Saved', value: fmt(snap.totalSaved) },
    { label: 'CC Debt', value: fmt(snap.ccDebt) },
    { label: 'Cash Flow', value: fmt(snap.income - snap.expenses - snap.totalDebtPayments) },
  ];

  const kpiHtml = kpis.map(k => `<div class="kpi"><div class="kpi-label">${k.label}</div><div class="kpi-value">${k.value}</div></div>`).join('');

  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Forged — Dashboard Snapshot</title><style>${PDF_STYLES}</style></head>
<body>
  <header>
    <div><h1>FORGED</h1><p class="meta">Command Center Snapshot &middot; ${snap.month}</p></div>
    <div class="right meta"><p>Exported ${exportDate}</p></div>
  </header>
  <div class="kpi-grid">${kpiHtml}</div>
  <footer>Generated by Forged &middot; app.treforged.com</footer>
</body></html>`;

  openPrintWindow(html);
}
